#pragma once

const char* AARootCertificate = "-----BEGIN CERTIFICATE-----\n"
                                "MIIDiTCCAnGgAwIBAgIJAMFO56WkVE1CMA0GCSqGSIb3DQEBBQUAMFsxCzAJBgNV\n"
                                "BAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1Nb3VudGFpbiBW\n"
                                "aWV3MR8wHQYDVQQKDBZHb29nbGUgQXV0b21vdGl2ZSBMaW5rMB4XDTE0MDYwNjE4\n"
                                "MjgxOVoXDTQ0MDYwNTE4MjgxOVowWzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNh\n"
                                "bGlmb3JuaWExFjAUBgNVBAcMDU1vdW50YWluIFZpZXcxHzAdBgNVBAoMFkdvb2ds\n"
                                "ZSBBdXRvbW90aXZlIExpbmswggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB\n"
                                "AQDUH+iIbwwVb74NdI5eBv/ACFmh4ml/NOW7gUVWdYX50n8uQQsHHLCNIhk5VV2H\n"
                                "hanvAZ/XXHPuVAPadE2HpnNqePKF/RDo4eJo/+rOief8gBYq/Z+OQTZeLdNm+GoI\n"
                                "HBrEjU4Ms8IdLuFW0jF8LlIRgekjLHpc7duUl3QpwBlmAWQK40T/SZjprlmhyqfJ\n"
                                "g1rxFdnGbrSibmCsTmb3m6WZyZUyrcwmd7t6q3pHbMABO+o02asPG/YPj/SJo4+i\n"
                                "fb5/Nk56f3hH9pBiPKQXJnVUdVLKMXSRgydDBsGSBol4C0JL77MNDrMR5jdafJ4j\n"
                                "mWmsa2+mnzoAv9AxEL9T0LiNAgMBAAGjUDBOMB0GA1UdDgQWBBS5dqvv8DPQiwrM\n"
                                "fgn8xKR91k7wgjAfBgNVHSMEGDAWgBS5dqvv8DPQiwrMfgn8xKR91k7wgjAMBgNV\n"
                                "HRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4IBAQDKcnBsrbB0Jbz2VGJKP2lwYB6P\n"
                                "dCTCCpQu7dVp61UQOX+zWfd2hnNMnLs/r1xPO+eyN0vmw7sD05phaIhbXVauKWZi\n"
                                "9WqWHTaR+9s6CTyBOc1Mye0DMj+4vHt+WLmf0lYjkYUVYvR1EImX8ktXzkVmOqn+\n"
                                "e30siqlZ8pQpsOgegIKfJ+pNQM8c3eXVv3KFMUgjZW33SziZL8IMsLvSO+1LtH37\n"
                                "KqbTEMP6XUwVuZopgGvaHU74eT/WSRGlL7vX4OL5/UXXP4qsGH2Zp7uQlErv4H9j\n"
                                "kMs37UL1vGb4M8RM7Eyu9/RulepSmqZUF+3i+3eby8iGq/3OWk9wgJf7AXnx\n"
                                "-----END CERTIFICATE-----";

const char* AAClientCertificate = "-----BEGIN CERTIFICATE-----\n"
                                  "MIIDPzCCAicCAgERMA0GCSqGSIb3DQEBCwUAMFsxCzAJBgNVBAYTAlVTMRMwEQYD\n"
                                  "VQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1Nb3VudGFpbiBWaWV3MR8wHQYDVQQK\n"
                                  "DBZHb29nbGUgQXV0b21vdGl2ZSBMaW5rMCYXETE0MDcwNDAwMDAwMC0wNzAwFxE0\n"
                                  "ODA4MDExMDIxMjMtMDcwMDBnMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZv\n"
                                  "cm5pYTEWMBQGA1UEBwwNTW91bnRhaW4gVmlldzEeMBwGA1UECgwVQW5kcm9pZC1B\n"
                                  "dXRvLUludGVybmFsMQswCQYDVQQLDAIwMTCCASIwDQYJKoZIhvcNAQEBBQADggEP\n"
                                  "ADCCAQoCggEBAOWghAac2eJLbi/ijgZGRB6/MuaBVfOImkQddBJUhXbnskTJB/JI\n"
                                  "12Ea22E5GeVN8CkWULAZT28yDWqsKMyq9BzpjpsHc9TKxMYqrIn0HP7mIJcBu5z7\n"
                                  "K8DoXqc86encncJlkGeuQkUA68yyp7RG7eQ6XoBHEjNmyvX13Y8NY5sPUHfLfmp6\n"
                                  "A2n+Jdmecq3L0GS84ctdNtnp2zSopTy0L1Gp6+lrnuOPAYZeV+Ei2jAvhycvuSoB\n"
                                  "yV6rT9wvREvC2TDncurMwR6ws44+ZStqkhnvDLhV04ray5aPplQwwB9GELFCYSRk\n"
                                  "56sm57uYSJj/LlmOMcvyBmUHVJ7MLxgtlykCAwEAATANBgkqhkiG9w0BAQsFAAOC\n"
                                  "AQEA1Bs8v6HuAIiBdhGDGHzZJDwO6lW0LheBqsGLG9KsVvIVrTMPP9lpdTPjStGn\n"
                                  "en1RIce4R4l3YTBwxOadLMkf8rymAE5JNjPsWlBue7eI4TFFw/cvnKxcTQ61bC4i\n"
                                  "2uosyDI5VfrXm38zYcZoK4TFtMhNyx6aYSEClWB9MjHa+n6eR3dLBCg1kMGqGdZ/\n"
                                  "AoK0UEkyI3UFU8sW86iaS4dvPSaQ+z0tmfUzbrc5ZSk4hYCeUYvuyd2ShxjKmxvD\n"
                                  "0K8A7gKLY0jP8Zp+6rYBcpxc7cylWMbdlhFTHAGiKI+XeQ/9u+RPeocZsn5jGlDt\n"
                                  "K3ftMoWFce+baNq/WcMzRj04AA==\n"
                                  "-----END CERTIFICATE-----";

const char* AAPrivateKey = "-----BEGIN PRIVATE KEY-----\n"
                           "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDloIQGnNniS24v\n"
                           "4o4GRkQevzLmgVXziJpEHXQSVIV257JEyQfySNdhGtthORnlTfApFlCwGU9vMg1q\n"
                           "rCjMqvQc6Y6bB3PUysTGKqyJ9Bz+5iCXAbuc+yvA6F6nPOnp3J3CZZBnrkJFAOvM\n"
                           "sqe0Ru3kOl6ARxIzZsr19d2PDWObD1B3y35qegNp/iXZnnKty9BkvOHLXTbZ6ds0\n"
                           "qKU8tC9Rqevpa57jjwGGXlfhItowL4cnL7kqAcleq0/cL0RLwtkw53LqzMEesLOO\n"
                           "PmUrapIZ7wy4VdOK2suWj6ZUMMAfRhCxQmEkZOerJue7mEiY/y5ZjjHL8gZlB1Se\n"
                           "zC8YLZcpAgMBAAECggEANfN+0abssnSSkQGj6Ol9e9Pke7ALp8qCpFpfOSdOrF9H\n"
                           "zU2GZnCi2hfbT36BDRVAxgaOMrHfrfqOmG+Wrm/EJz7g2J/poSd7ECxamZcXcPRU\n"
                           "1+X6VKnW3944zwZK1z2Ue2YthY6110yeGlwndv3rSuJD7dPE/Pq72QpJYiD9NCL1\n"
                           "DoX98hDpl570C8bpD/8I4lgD2YqGcLmR6cHaKx0gQjxfr2gPY22uu0rDsriTPUQX\n"
                           "og01iG7iwbFZkGD0/N0LdBHQtfXclDWZvi3sm/1Td2d1GmKw5QGl69BAxNlyrpo9\n"
                           "TCYIXcop5/ZJTvoJ06wxKBmimYtWJZMuKlC6eDg9AQKBgQD1RIj4fkpuL1D5Cj1b\n"
                           "ceNUNAcsRNuDNZmo3WvDVBNVGQaJKQcm0EzUwc94UKuWZ/lTBOJyBYUbdsiQTHsd\n"
                           "uHk0bUmP1II7/k7cieP4sGGZEV9ouB6PC8N3wPryncyBQdRAUsoaOsWu/bzAP08w\n"
                           "q08LxwtweUiTzubPjnwKdBUV0QKBgQDvrMZsHmn6PLIaC1kpvWLeIAC4ZHOJffD8\n"
                           "++ap5djTDLP6tmve7eZVL1XuVhsPag5JlBs1bPenvqcTMTqP4my33W6GSXz8dqHq\n"
                           "X271tY7Zw+pf1rjTYZ8khufrdMia5zSAKTZ27hofVobDJWDJwo+ijQLcIwwkVN3K\n"
                           "COqdU53J2QKBgGP8jY4oBfXHSk5MU1kdI5ynHSl55Lcnub2yjoTxmHP/oL93v1ee\n"
                           "YUP2wrp8wIavWl/yxNHQ2EOq9/aDh0lFc/vgdbWx32nPsZyMhihS12bMQ0XwkVyl\n"
                           "YglG3cbcd4tWJ84VMhjhTseY30LMTF895xqZCVvPxbukBEom/wBP9GyRAoGAXSR6\n"
                           "9DeZnesKl/6DByqXipVLUl2PXQZ5qgdHLA2sBtDv/OX54+f2VHKR5Y7G82WW6ddJ\n"
                           "/6g6UpFQIrBF/vbSo13FfyB+FysPX6L43zpQqqZtphMvPs64ZxyacrGu6CwkBg5+\n"
                           "IRgFRNp+gsY66A3ZfiVo0B46sL/edY6jhsKhFnkCgYEAqHKJM0GrxITZYLMjCXZC\n"
                           "udZvONe14MnYUJfxpQ3CLgpBq5QbTQq8ITtVAvd7PHrdHzW4B4+yKroTQ2gn6ev0\n"
                           "nTFBkYuHpa2CvVSumc30qfZpeKMatdmbQC2FVEPSOQS5cx6B7YYS0nW9nRon+Sbt\n"
                           "GQ5XKUTGTaUvJR1gYDDMrlM=\n"
                           "-----END PRIVATE KEY-----";

const char* AAPhoneCert = "-----BEGIN CERTIFICATE-----\n"
                          "MIIDLDCCAhQCAgMIMA0GCSqGSIb3DQEBCwUAMFsxCzAJBgNVBAYTAlVTMRMwEQYD\n"
                          "VQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1Nb3VudGFpbiBWaWV3MR8wHQYDVQQK\n"
                          "DBZHb29nbGUgQXV0b21vdGl2ZSBMaW5rMB4XDTE0MDcwNDAwMDAwMFoXDTIyMDgy\n"
                          "NDEyMjkxMlowXDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAU\n"
                          "BgNVBAcMDU1vdW50YWluIFZpZXcxEzARBgNVBAoMCkNhclNlcnZpY2UxCzAJBgNV\n"
                          "BAsMAjUzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz/sgFFGUFIFz\n"
                          "oMZwkicaH8dY4mnRLMP+m4KszLyxN/1FRWATM+LVwDeWvlS3ZqzyKeUPmx5t+WUF\n"
                          "Mx15Q4/OlzKoyhD6nmx3eunlP6dp1bO0LLJjOFPny4VKgSrrPlUNgwrFga5Pl7wC\n"
                          "s8Dh5ObQUfp7lLytsb3RcGcRG2039L6ZZZghpYc5qGV+NqRsIdA3ZirvNmAcAgxC\n"
                          "szUyztCbrtMaWXIo78p0zgEEaCExN5ekMpqBCcMVo0bXWWiYcyxWCpNq77qTSGf2\n"
                          "CZEQE/BLtw/0b+1wYGQLTf0Mq+SGcRzIUrK5wsHEzCxs8KXQfAv0KlnJdiRPR74S\n"
                          "ln/9geVooQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCAq5uOCPCpleMNPqnHX9oY\n"
                          "7IUaMW1zzpjjWseuX/6MgyI72kDhHDzg/XhYkgrEbfsy61wpnsqzp9LGbYylKVDD\n"
                          "8LsEyUMNjfUD0StCbJEed/DdaBITtRktuetJ22bpE2nX/DjJYMsR3UVt/l1HL+Wh\n"
                          "HzGurXVPB7l4ZMtbaz3SPZbG+iIfHwQKP/J3XOnttk5ihiIBD86gBfZn9oPTYrIX\n"
                          "e2LrG6LbQUtVqqBYqg291c5ECFTeOUegF9WAx6UH9eztEH+emOWxosv1zE6Ssjs9\n"
                          "jrFuvbuEvTsRaVEJve2+YIKaPzm4tnIGAs5MlpRC51P2ImI7PunxfguAvK3lBEyj\n"
                          "-----END CERTIFICATE-----";

const char* AAPhonePrivateKey = "-----BEGIN PRIVATE KEY-----\n"
                                "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDP+yAUUZQUgXOg\n"
                                "xnCSJxofx1jiadEsw/6bgqzMvLE3/UVFYBMz4tXAN5a+VLdmrPIp5Q+bHm35ZQUz\n"
                                "HXlDj86XMqjKEPqebHd66eU/p2nVs7QssmM4U+fLhUqBKus+VQ2DCsWBrk+XvAKz\n"
                                "wOHk5tBR+nuUvK2xvdFwZxEbbTf0vpllmCGlhzmoZX42pGwh0DdmKu82YBwCDEKz\n"
                                "NTLO0Juu0xpZcijvynTOAQRoITE3l6QymoEJwxWjRtdZaJhzLFYKk2rvupNIZ/YJ\n"
                                "kRAT8Eu3D/Rv7XBgZAtN/Qyr5IZxHMhSsrnCwcTMLGzwpdB8C/QqWcl2JE9HvhKW\n"
                                "f/2B5WihAgMBAAECggEBALAUv2MUchcuRfO/Lb0/J6nx/zmpNvP8d4m3h47KzgtF\n"
                                "/SiwH3HVQPy8034OgTuHfnqjuKOujpMPyOgusuTVUqXFuQtidpw73qgMcA+FMGBC\n"
                                "BW+2E7SzrNIs5hgXexTJs2fXbcHODwq6nVsMGPPPyl0tgQU6/J83wqK0T9J1lGM6\n"
                                "mA/1Pz1wJm3BtWJqzY7Qc76zRJ1w3u47APJNFTGmcON+HMHC2GaMQg4F08LFx7gp\n"
                                "wmXpyUg8nIGFB1k8trN+6ACvoFbO+hky7P5KOyGpSk8MMQ0tyHKmg7C3SCVHpokg\n"
                                "GxCgDct6mcyOHn0fWDEXoD7j44+3v9Ek1Dpni5G/jkUCgYEA7QSxebseq29HamNz\n"
                                "ukf3YDQxt4DaW9tRjT7lsUziVD1hUhXHvTe5J0I3YtxiCnJm16qM2MrM4OZvbJtz\n"
                                "fBf2cprXVPLR8DFYHSn3rDnRXFX2Uu6gzocfNLkE6/mwsffD+haZG3Y1AKkOiqFb\n"
                                "ZCv8burIXqe6mSAMaY7njgbZwvsCgYEA4KMc8kBBt3nfVAtxB88WZDsgmZ3T+0JM\n"
                                "JWT2+Q3K2fOyxZ8EcOhlDQik0WvPyWi6BsFY76B55V6T7j65sskdTIKAQNSJN+CE\n"
                                "SUenjqjwlGuMVxdOUDo/bw4Y1zMIFjonC1P/0y9rthBuVMFiDJnPNNOMOEzZhqWJ\n"
                                "5EZxHvLw0BMCgYEAlWks+6DSj51hdpZk4Jv3PEUKxjPK8rbJrPFmWCMwVYwv6k/i\n"
                                "jswuwqnCQmbMwuslG3Tevtbw2iFJQjyoSyTL7ajgbyN25iQk+JV5FK+J49wooFTf\n"
                                "N/ID4Pd1O9A166pVdzSBpccZWGY5zXg0JWx4/+6vCsRPI7IJQQ2duHFnGrsCgYBr\n"
                                "wTKobfRYG6jqOtbMZSUbjVVU+uVtmF7IbUcfLuOIayLtMxtBQej/OI8/OdUhiw/5\n"
                                "H5QW1kbCpPyXAxW20kwwoET/VDRCTnuGX03b2+QTfgeC21Ygm+BD2GJIEF2ns9t4\n"
                                "zqFf31ZurjEOjPkIjFtdvsB7XTnXId8kVjn7G5QyawKBgCmOEWavSitiyqeYiGUN\n"
                                "7TAY+nnisxkGPa7JZg1Q32E8QysHsAjNQV3XKjXxICRt8MjDHaJ10CnHJAoio1r2\n"
                                "+X55cjK4/JWFHSdTC10CWv2lyJVXw+iwKQ4vDhSfG3PMnirZ5NdkZ/67xrHblww3\n"
                                "H6rHQ/1+7tZeGLa5KN8d8/Yr\n"
                                "-----END PRIVATE KEY-----";